apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: en5rxre6x-go 
  janus-idp.io/tekton: en5rxre6x-go
  backstage.io/kubernetes-id: en5rxre6x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: en5rxre6x-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  